### PR TITLE
Support 8.2.5 BattleNet API in PlayerNames module

### LINKED ISSUE #19: Error when sending or recieving Message from BNet Account
I get an error every message i send to a BattleNet account on my fl.
Seems like it tries to colorize the name, but has no class.

``38x Prat-3.0-3.7.36\services\classcolor.lua:19: attempt to index local 'class' (a nil value)
Prat-3.0-3.7.36\services\classcolor.lua:19: in function `GetClassGetColor'
Prat-3.0-3.7.36\modules\PlayerNames.lua:1460: in function `GetClassColor'
Prat-3.0-3.7.36\modules\PlayerNames.lua:1351: in function `Class'
Prat-3.0-3.7.36\modules\PlayerNames.lua:1519: in function `FormatPlayer'
Prat-3.0-3.7.36\modules\PlayerNames.lua:1623: in function `?'
...tip\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...tip\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...tip\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...tip\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...tip\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Prat-3.0-3.7.36\addon\addon.lua:626: in function <Prat-3.0\addon\addon.lua:567>
(tail call): ?
FrameXML\ChatFrame.lua:3012: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>``

### PR DESCRIPTION
**Pull request by Mitalie**
A wrapper function provides necessary information in same format in both 8.2.5 and classic. Tested to work in both games. Fixes #19.

This includes one behavior change: people who are or appear offline now use the same fallback color as those who are online but not on WoW, instead of skipping name coloring entirely.

This PR is ready to merge as is, but it may be worth considering what is the best way to handle mainline and classic support if/when the APIs diverge further. Should usage-specific wrapper functions like this be used, should we attempt to emulate one API with the other, or should there be separate branches?

### CODE REVIEW

**Comment by Jared87** [comment]
I've installed this version, it works fine for me.

**Comment by AndyGrant** [comment]
This fix breaks the colouring component of the addon for me. Player names are no longer given their class colour in any messages in the chat log, for Retail wow

**Comment by Mitalie** [comment]
@AndyGrant are you getting any errors? How did you apply the fix?

**Comment by AndyGrant** [comment]
I have one error when logging in. I can get that information when I log in this evening. I suspect it's more likely that I applied the change wrong. 

I took your modified version of `modules/PlayerNames.lua` and used it to replace the existing version in my Prat folder in the add-ons area. 

Doing this DID fix the battlenet errors. Do I need to update multiple files? I'm not familiar with this project structure.

**Comment by Mitalie** [comment]
Just a guess, but it could be an issue with the localization data - the file in the git repo only has an English debug locale, the proper locales are added in CI build and uploaded to Twitch/WoWI. If the debug locale is outdated/broken or your WoW is not in English it might throw errors during load and leave the module in a broken state.

**Comment by Mitalie** [comment]
Modified file with the localizations https://gist.github.com/amakinen/b9bc85f91b0d5aa019218f8f4df1cd51.
This is what I have in my addons dir currently and it seems to work fine.

**Comment by AndyGrant** [comment]
That appears to work. My apologies for not understanding how to update the add-on correctly. No errors thus far after testing out various chat functions for a bit.

**Comment by sylvanaar** [comment]
Hi guys, thanks for all your help with this PR. I will be testing shortly

**Pull request merged**
