### PR TITLE
Apply fixes for prepatch

### PR DESCRIPTION
**Pull request by Vashidu**
Fixed the guildroster issue, and addon now works.

### CODE REVIEW

**Comment by Zetaprime82** [comment]
Do you have a file that we can just download?

**Comment by ChristopheBoucaut** [comment]
> Do you have a file that we can just download?

1 - Click on "Vashidu:master" on top
2 - You will come on this page : https://github.com/Vashidu/prat-3-0
3 - Click on "Code" > "Download ZIP"

**Comment by mcoakley** [comment]
I can confirm that I installed this version of the addon and the majority of the issues I was seeing with Prat-3.0 with the latest WoW pre-patch version are now gone.

**Comment by soapnrope** [comment]
`InviteUnit` is also deprecated for ` C_PartyInfo.InviteUnit(name)`

This ir regarding `Invites.lua` to get working inv links in chat.

**Comment by sylvanaar** [comment]
Thanks for the PR!

**Comment by sylvanaar** [comment]
Really appreciate all the work everyone has done - you know I was completely consumed at work for the past 3 months, and you guys have really shown so much support! Thank you!

**Comment by Zetaprime82** [comment]
i guess we will see a release in a few days then 👍

**Pull request merged**
