### PR TITLE
Hiding default UI timestamps without breaking Communities UI - setfenv solution

### PR DESCRIPTION
**Pull request by Mitalie**
This is an attempt to fix issue #21 using the setfenv solution described in the ticket.

Marking as draft because I'd like to make it toggled with module enable and disable.

Not really sure about showing an addon name in the warning - would it just end up blaming the first addon to load newest AceHook if someone indeed does hook CF_MEH before we can setfenv?

Also need help with localization of the message - the entry needs to be added to curseforge before build or the code will throw an error when attempting to use the entry, right?

### CODE REVIEW

**Comment by sylvanaar** [comment]
Should we continue this PR?

**Comment by Mitalie** [comment]
Sure. I've held off further work while waiting for feedback on either this, or the other ideas in #21. I've been using these changes locally since I made the PR, and haven't noticed any problems, but of course that's only my personal addon setup that doesn't include any other CF_MEH hooks.

For enabling and disabling, my idea is to do the setfenv call in SetModuleInit callback, and then flip `CHAT_TIMESTAMP_FORMAT` in the custom env table between false (block) and nil (fallback to _G) on enable and disable. Does that sound good?

**Comment by sylvanaar** [comment]
You are right. It looks like it has the potential to cause some issues. I guess the next step would to let it cause one and see just what they look like.

**Comment by sylvanaar** [comment]
I think we should try it out - it doesn't break anything for me either

**Comment by Mitalie** [comment]
I implemented restoring Blizzard timestamps in https://github.com/amakinen/prat-3-0/commit/043ac3f6ead45c511d16b660bffe2ccc6360fffb but upon further testing and thought I realized it's unlikely anyone wants exactly that: Blizzard timestamps show on non-Prat-handled events like CHAT_MSG_EMOTE, but not for anything processed by Prat. If someone loads but disables the Timestamps module, the desired result is probably no timestamps at all in chat window (while leaving Blizzard setting for Communities UI).

I still moved the setfenv call into module init so it's done at earlier possible moment for smaller chance to fail, and not unnecessarily redone on module toggle.

**Comment by sylvanaar** [comment]
Ok - I am going to hold onto it until later, when I have more time to revert if it causes trouble.

**Comment by Mitalie** [comment]
No problem. There's still the TODO item about a warning message if we can't find the original CF_MEH to call setfenv on.

Message could be something like `PL["Can't disable Blizzard timestamps because another AddOn has hooked the required function."]` but it'll cause runtime error for missing localization if I add it now and that branch gets executed.

**Comment by sylvanaar** [comment]
Thank you for all the hard work!

**Comment by Mitalie** [comment]
Merges cleanly after `git revert 930c939`, or would you prefer me to rebase this instead?

**Comment by sylvanaar** [comment]
This seems to create a whole lot of noise in the taint log.

```
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame1:OnEvent()
5/4 10:51:14.469  Execution tainted by Prat-3.0 while reading Prat - Interface\AddOns\Prat-3.0\modules\Timestamps.lua:303
5/4 10:51:14.469      Interface\AddOns\Prat-3.0\addon\addon.lua:701
5/4 10:51:14.469      Interface\AddOns\Prat-3.0\addon\addon.lua:663
5/4 10:51:14.469      Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame1:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      *:OnEvent:1 ChatFrame2:original_OnEvent()
5/4 10:51:14.469      Interface\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3302
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame3:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame4:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame5:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame6:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame7:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame8:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame9:OnEvent()
5/4 10:51:14.469  Execution tainted by Ace3 while reading ChatFrame_MessageEventHandler - Interface\FrameXML\ChatFrame.lua:3018 ChatFrame_OnEvent()
5/4 10:51:14.469      ChatFrame10:OnEvent()
```

**Comment by Mitalie** [comment]
The taintlog spam is expected and unavoidable. Even with the timestamps module set to not load, [prat core](https://github.com/sylvanaar/prat-3-0/blob/930c939eafd02157170ae294e78ca6bc642567da/addon/addon.lua#L435) hooks the same function, tainting execution when called. This has been the same for over 10 years and has not been a problem as far as I know.

While there's a technical difference between tainting the function closure with setfenv, and tainting the global variable through which the function is accessed, the effect is same: execution is already tainted when entering the function, and remains tainted after returning from it.

**Comment by sylvanaar** [comment]
Ok - sorry for taking so long to approve this. Thank you for your help!

**Pull request merged**
