### PR TITLE
Fix lua error in ChannelSticky config options

### PR DESCRIPTION
**Pull request by Shauren**
CHAT_MSG_INSTANCE_CHAT global does not exist, its just INSTANCE_CHAT

### CODE REVIEW

**Comment by sylvanaar** [comment]
Thank You for the PR!

**Comment by Addonman** [comment]
If it was meant to fix bug #10 it didnt work for me. Maybe i did something wrong but that didnt fix it for me.

**Comment by Shauren** [comment]
@Addonman no, its a different issue/module

**Comment by Addonman** [comment]
Its same  module since only solutions i heard so far was to remove all sticky channels then reload.If was short fix that didnt worked after next logging in  into game .I guess your solution was for "CHAT_MSG_CHANNEL_NOTICE" apperance after every chanell?

**Comment by Shauren** [comment]
No, it was breaking only the options panel for sticky

**Pull request merged**
